services:
  dev-db:
    container_name: lamariaelena
    image: postgres:13
    environment:
      - POSTGRES_USER=mariaelena
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=lamariaelena3
    ports:
      - 5434:5432
    restart: always
  test-db:
    container_name: test_lamariaelena
    image: postgres:13
    environment:
      - POSTGRES_USER=mariaelena
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=lamariaelena3 
    ports:
      - 5435:5432
    restart: always